name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --platform manylinux2014_aarch64 --target ./python --python-version 3.12 --only-binary=:all: Flask boto3 langchain langchain-postgres langchain-aws langchain-community psycopg2-binary

      - name: Package layer
        run: |
          zip -r layer.zip python

      - name: Publish layer
        run: |
          aws lambda publish-layer-version --layer-name flask-dependencies --description "Dependencies for Flask Lambda function" --zip-file fileb://layer.zip --compatible-runtimes python3.12

      - name: Copy application files
        run: |
          cp -r ./* ./package/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pip install awscli
          cd package
          aws lambda update-function-code --function-name flask-lambda --zip-file fileb://function.zip
